platform :ios, '16.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/expo/expo.git'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

config = use_native_modules!

target 'MyCliTest' do
  use_expo_modules!

  # Enable Hermes
  use_react_native!(
    :path => config[:reactNativePath], 
    :app_path => "#{Pod::Config.instance.installation_root}/..", 
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  target 'MyCliTestTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
